export const currencyData = [
   { name: 'USD', smText: 'US Dollar' },
   { name: 'BRL', smText: 'Brazil' },
   { name: 'INR', smText: 'India' },
   { name: 'EUR', smText: 'Euro' },
   { name: 'RUB', smText: 'Russia' },
   { name: 'NGN', smText: 'Nigeria' },
   { name: 'IDR', smText: 'Indonesia' },
   { name: 'BDT', smText: 'Bangladesh' },
   { name: 'PHP', smText: 'Philippine' },
   { name: 'VND', smText: 'Vietnam' },
   { name: 'THB', smText: 'Thailand' },
   { name: 'KZT', smText: 'Kazakhstani tenge' },
   { name: 'MAD', smText: 'Morocco' },
   { name: 'ZAR', smText: 'South Africa' },
   { name: 'PLN', smText: 'Poland' },
   { name: 'CUP', smText: 'Cuba' },
   { name: 'KRW', smText: 'Korea' },
   { name: 'JPY', smText: 'Japan' },
   { name: 'GBP', smText: 'United Kingdom' },
   { name: 'HRK', smText: 'Croatia' },
   { name: 'ISK', smText: 'Iceland' },
   { name: 'HUF', smText: 'Hungary' },
   { name: 'NOK', smText: 'Norwegian' },
   { name: 'NZD', smText: 'New Zealand Dollar' },
   { name: 'MXN', smText: 'Mexico Peso' },
   { name: 'AUD', smText: 'Australia Dollar' },
   { name: 'TRY', smText: 'Turkey Lira' },
   { name: 'IRR', smText: 'Iran Rial' },
   { name: 'AED', smText: 'UAE-Dirham' },
   { name: 'UAH', smText: 'Ukraine Hryvnia' },
   { name: 'CZK', smText: 'Czech Republic Koruna' },
   { name: 'LKR', smText: 'Sri Lanka Rupee' },
   { name: 'ILS', smText: 'Israel Shekel' },
   { name: 'EGP', smText: 'Egypt Pound' },
   { name: 'PKR', smText: 'Pakistan Rupee' },
   { name: 'GHS', smText: 'Ghana Cedi' },
   { name: 'VEF', smText: 'Venezuela Bolívar' },
   { name: 'PEN', smText: 'Peru Sol' },
   { name: 'RON', smText: 'Romania Leu' },
   { name: 'BGN', smText: 'Bulgaria Lev' },
   { name: 'RSD', smText: 'Serbia Dinar' },
   { name: 'CLP', smText: 'Chile Peso' },
];
