version: '3.8'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000
    depends_on:
      - server