export const AchieveAr = [
   { url: '/achieve/achieve_1.webp', id: 1 },
   { url: '/achieve/achieve_2.webp', id: 2 },
   { url: '/achieve/achieve_3.webp', id: 3 },
   { url: '/achieve/achieve_4.webp', id: 4 },
   { url: '/achieve/achieve_5.webp', id: 5 },
   { url: '/achieve/achieve_6.webp', id: 6 },
   { url: '/achieve/achieve_7.webp', id: 7 },
   { url: '/achieve/achieve_8.webp', id: 8 },
   { url: '/achieve/achieve_9.webp', id: 9 },
   { url: '/achieve/achieve_10.webp', id: 10 },
   { url: '/achieve/achieve_11.webp', id: 11 },
   { url: '/achieve/achieve_12.webp', id: 12 },
   { url: '/achieve/achieve_13.webp', id: 13 },
   { url: '/achieve/achieve_14.webp', id: 14 },
   { url: '/achieve/achieve_15.webp', id: 15 },
   { url: '/achieve/achieve_16.webp', id: 16 },
   { url: '/achieve/achieve_17_BTC.webp', id: 17 },
   { url: '/achieve/achieve_17_DOGE.webp', id: 18 },
   { url: '/achieve/achieve_17_EOS.webp', id: 19 },
   { url: '/achieve/achieve_17_ETH.webp', id: 20 },
];
